### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cwmaloney** [andrewcourtice/vuetiful#17]
Hi Andrew,

First, thanks for your contribution of this project to the world.

Sorry if I am missing it - I do not see a license file for vuetiful.  Many potential users will not be able to use vuetiful without the definition of the licensing.  Please consider adding a license file for the repository.  you might review https://help.github.com/articles/licensing-a-repository/ for suggestions.  That document reflects my concerns: "You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work."

Thanks for your time,
chris

**Comment by andrewcourtice** [comment]
Hi Chris

Thanks for your feedback and advice. I completely forgot about licensing the repo. I have added an MIT license in now so you are free to copy and distribute my code accordingly.

Thanks
