### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by arthurtyukayev** [andrewcourtice/vuetiful#19]
I understand that this is a framework and the CSS is sort of built in. I would love to be able to use the javascript in this datatable and pair it with a framework like Semantic or Bootstrap. 

Is this at all possible?

**Comment by mcamiano** [comment]
If the component's styles were scoped they'd be less likely to interact with a different framework in unexpected ways. The modal styles, for instance, clobber Bootstrap 4's default modal positioning.  cf https://vue-loader.vuejs.org/en/features/scoped-css.html

**Comment by DelfsEngineering** [comment]
Do you know a work around? I am finding the CSS messes up the rest of my web app. So it becomes a deal breaker as it stands ...
