### ISSUE TITLE
array.find() not widely supported

### ISSUE THREAD

**Issue by KuriosCurious** [andrewcourtice/vuetiful#8]
Found this project because of the datatable. Great work you are doing here. Very exciting!
I thought you should know, in case you already don't, that the find() method used isn't widely supported.
According to [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/find), it's not supported in IE and most mobile browsers.
Might want to reconsider using that as it makes the library unusable for a lot of people.

**Comment by andrewcourtice** [comment]
Thanks @KuriosCurious! That completely slipped my mind. I've polyfilled it now.
